config/routes.rb
Rails.application.routes.draw do
  root 'responses#new'
  resources :analyses, only: [:show]
  resources :responses, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/analysis.rb
class Analysis < ApplicationRecord
  belongs_to :response
end

# == Schema Information
#
# Table name: analyses
#
#  id          :integer          not null, primary key
#  phrase      :string
#  score       :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  response_id :integer
#
# Indexes
#
#  index_analyses_on_response_id  (response_id)
#
# Foreign Keys
#
#  fk_rails_...  (response_id => responses.id)
#

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/response.rb
class Response < ApplicationRecord
  has_one :analysis
end

# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  text       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  before_action :set_analysis, only: [:show, :edit, :update, :destroy]

  # GET /analyses
  # GET /analyses.json
  def index
    @analyses = Analysis.all
  end

  # GET /analyses/1
  # GET /analyses/1.json
  def show
    @response = Response.where(id: @analysis.response_id).first
    @analyses = Analysis.where(response_id: @response.id)
  end

  # GET /analyses/new
  def new
    @analysis = Analysis.new
  end

  # GET /analyses/1/edit
  def edit
  end

  # POST /analyses
  # POST /analyses.json
  def create
    @analysis = Analysis.new(analysis_params)

    respond_to do |format|
      if @analysis.save
        format.html { redirect_to @analysis, notice: 'Analysis was successfully created.' }
        format.json { render :show, status: :created, location: @analysis }
      else
        format.html { render :new }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analyses/1
  # PATCH/PUT /analyses/1.json
  def update
    respond_to do |format|
      if @analysis.update(analysis_params)
        format.html { redirect_to @analysis, notice: 'Analysis was successfully updated.' }
        format.json { render :show, status: :ok, location: @analysis }
      else
        format.html { render :edit }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analyses/1
  # DELETE /analyses/1.json
  def destroy
    @analysis.destroy
    respond_to do |format|
      format.html { redirect_to analyses_url, notice: 'Analysis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analysis
      @analysis = Analysis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analysis_params
      params.require(:analysis).permit(:score, :phrase, :response_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)
    if @response.save
      id = @response.id
      text = @response.text
      comprehend = Aws::Comprehend::Client.new(region: 'us-east-1')
      analysis = comprehend.detect_key_phrases(text: text, language_code: 'en')
      analysis.key_phrases.each do |struct|
        Analysis.create(score: struct['score'].to_f, phrase: struct['text'],
                        response_id: id)
      end
    end
    @analysis = Analysis.where(response_id: id).first
    redirect_to @analysis
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:text)
    end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/analyses/_form.html.erb
<%= form_for(analysis) do |f| %>
  <% if analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analysis.errors.count, "error") %> prohibited this analysis from being saved:</h2>

      <ul>
      <% analysis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comprehend %>
    <%= f.text_field :comprehend %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/analyses/edit.html.erb
<h1>Editing Analysis</h1>

<%= render 'form', analysis: @analysis %>

<%= link_to 'Show', @analysis %> |
<%= link_to 'Back', analyses_path %>

app/views/analyses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Analyses</h1>

<table>
  <thead>
    <tr>
      <th>Comprehend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analyses.each do |analysis| %>
      <tr>
        <td><%= analysis.comprehend %></td>
        <td><%= link_to 'Show', analysis %></td>
        <td><%= link_to 'Edit', edit_analysis_path(analysis) %></td>
        <td><%= link_to 'Destroy', analysis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analysis', new_analysis_path %>

app/views/analyses/new.html.erb
<h1>New Analysis</h1>

<%= render 'form', analysis: @analysis %>

<%= link_to 'Back', analyses_path %>

app/views/analyses/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Response Analysis</h1>
<br />
<strong>Text:</strong> <%= @response.text %>
<br />
<br />
<strong>Key Phrases:</strong>
<br />
<% @analyses.each do |analysis| %>
  <br />
  <strong>Phrase:</strong> <%= analysis.phrase %><br />
  <strong>Score:</strong> <%= analysis.score.to_f %><br />
  <br />
<% end %>

<br />
<%= link_to 'Enter New Responses', new_response_path, class: 'btn btn-primary btn-lg', role: "button" %>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonComprehend</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/responses/_form.html.erb
<%= form_for(response) do |f| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_area :text, class: 'form-control', rows: 5 %>
  </div>

  <div class="actions">
    <%= f.submit 'Analyze Responses', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.text %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>Input Responses</h1>
<br />
<%= render 'form', response: @response %>
<br />

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @response.text %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>